### ISSUE TITLE
Chrome Extension 뼈대 만들기

### ISSUE THREAD

**Issue by ga0hyeon** [ga0hyeon/CN-SIDE-1#1]

**Comment by ga0hyeon** [comment]
#2 가 진행되고 난 뒤 최종 마무리될 수 있습니다.

**Comment by ga0hyeon** [comment]
@sprinter707님이 좋은 의견 주셨어요 :) 

익스텐션의 형태는 youtube music 처럼 PWA로 만들어봅시다.

**Comment by sprinter707** [comment]
https://github.com/ga0hyeon/CN-SIDE-1/tree/feature/11-main-lobby
요 브랜치에서 대강 틀은 작성해보았습니다

**Comment by sprinter707** [comment]
React + Zustand 뼈대 만들기 를 스토리 분리
https://github.com/ga0hyeon/CN-SIDE-1/issues/15

**Comment by yunju-choi** [comment]
팝업 사이즈 800x600 제한🥺🥺🥺🥺
https://developer.chrome.com/docs/extensions/reference/browserAction/
![Image](https://user-images.githubusercontent.com/62147394/234029074-c2955a53-9fe6-4460-ac1f-975c64fd3433.png)
