### ISSUE TITLE
Tailwind 사용성 검토하기 (조건부 class 등 우리가 원래 일하던 방식으로 사용할 수 있는지 확인하기)

### ISSUE THREAD

**Issue by ga0hyeon** [ga0hyeon/CN-SIDE-1#3]

**Comment by yunju-choi** [comment]
Tailwind css : 별도 css 파일로 스타일을 정의하지 않고 tailwind에서 미리 만들어 놓은 css 조합을 이용하는 방법
ex. <div class="text-green-600"}></div>

1) 별도 css 파일 정의하지 않아 클래스 지정이 필요없음

2) 정의되지 않은 스타일로 적용하려면 특정 값을 주입하여 커버가 되는 경우도 있고 별도 코드 추가가 필요한 경우도 있음
: https://tailwindcss.com/docs/adding-custom-styles
ex. 특정값 사용
```
   <div class="top-[123px]">
   <div class="bg-[#bada55] text-[22px]">
```
ex. tailwind.config.js 수정
https://velog.io/@boorook/Tailwind-CSS%EC%97%90%EC%84%9C-%EC%BB%A4%EC%8A%A4%ED%85%80-%EC%BB%AC%EB%9F%AC-%EC%84%A4%EC%A0%95

3) 특정 스타일을 반복해서 사용하고 싶은 경우 @apply 이용하여 적용 가능함
```
@tailwind base;
@tailwind components;

.nav_link {
  @apply font-semibold text-gray-700  hover:border-gray-600 border-b-2 border-transparent;
  a {
    @apply block py-7 px-4;
  }
}

@tailwind utilities;
```
4) 조건부 클래스
```
<div class={`${error ? "text-red-600" : "text-green-600"}`}></div>
```
5) 상태에 대해 적용할때 번거로움
```
focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 hover:outline-none hover:border-sky-500 hover:ring-1 hover:ring-sky-500
```
6) 인터랙티브 웹 구현을 해야하려면 여러 예제를 참고할 필요가 있는데 매번 변환이 필요하고 제공해주는걸 사용하는 입장이라 자유도의 문제가 있을 수 있음

**Comment by yunju-choi** [comment]
일단 한번 작은 부분이라도 적용해보는 것으로~~~🏃‍♀️🏃‍♀️🏃‍♀️
