### ISSUE TITLE
적합한 보드게임 선정하기

### ISSUE THREAD

**Issue by ga0hyeon** [ga0hyeon/CN-SIDE-1#4]

**Comment by sprinter707** [comment]
루미큐브

코드네임

할리갈리

마피아
- 아발론, 스파이폴

**Comment by ga0hyeon** [comment]
규칙이 복잡한 것은 거르면 좋겠습니다.

디자인이 많이 필요한 것도 거르면 좋을 것 같습니다.

**Comment by minwoocho** [comment]
할리갈리/마피아가 제일 규칙이 간단할 것 같습니다.

개인적으로 생각되는 규칙 복잡도로는
코드네임 > 루미큐브 > 마피아 > 할리갈리 인 것 같습니다.

**Comment by minwoocho** [comment]
할리갈리로 결정
