### ISSUE TITLE
API Gateway, Lambda, Redis (또는 다른 어떤 저장소) 구성하기

### ISSUE THREAD

**Issue by ga0hyeon** [ga0hyeon/CN-SIDE-1#7]

**Comment by ga0hyeon** [comment]
팀 AWS 계정을 사용하는 것도 후보입니다.

**Comment by minwoocho** [comment]
백엔드를 node.js로 가기로 했다면, Serverless로 가는 것도 나쁘지않을 것 같습니다.(백엔드에 많은 에포트가 들 것 같지 않다는 가정하에)

**Comment by ga0hyeon** [comment]
비용 관련해서 알아보기 (람다, 레디스)

**Comment by ga0hyeon** [comment]
api gateway 는 소켓통신을 사용하는 경우 일반 rest api 보다 가격이 좀 더 높아짐 (당연한걸지도..?)
#6 과 함께 @sprinter707 님이 제안해주신 firebase 서비스 검토하려고함

**Comment by ga0hyeon** [comment]
https://firebase.google.com/pricing?hl=ko


![Image](https://user-images.githubusercontent.com/23169601/230517290-2732ed64-6c33-4529-9604-49898aa96b81.png)

**Comment by ga0hyeon** [comment]
api gateway 가 반드시 필요한가? 확인해보기

**Comment by ga0hyeon** [comment]
게이트웨이 비용에 대한 고민은 ㅎㅎ 하지 않아도 .. . . . 됩니당

**Comment by ga0hyeon** [comment]
- Lambda만 사용해서 Socket 통신을 구현할 수 있는가?
  - (가설) Yes, 하지만 15분이 지나면 끊어지지 않을까? 15분이 차기 전에 다음 연결로 넘겨주는 트릭이 필요하지 않을까?
- 지금 우리 컨셉에서 Api Gateway Websocket 의 장점은 무엇인가?
  - (가설) Lambda Authorizer로 부적절한 Lambda 과다 호출을 막을 수 있음
  - (반론) Authorizer에서 확인하는 정보의 수준이 origin 정도라면, Lambda 에서도 설정할 수 있음
  - (사실) 연결의 시작과 끝에 API Gateway에서 지정된 route의 lambda를 호출해줌 
  - (사실) 과다 호출 (429 too many requests)을 내어 비용 초과를 사전에 방지함 
  - (사실) 다른 AWS 서비스 (로깅) 연동 측면, 환경별 배포 자동화 측면에서는 메리트가 없음

- 참고자료
  - [자습서](https://docs.aws.amazon.com/ko_kr/apigateway/latest/developerguide/websocket-api-chat-app.html)

**Comment by ga0hyeon** [comment]
![Image](https://user-images.githubusercontent.com/23169601/231334323-cdc663dc-c3d4-498d-8b1a-91191eee8532.png)

**Comment by ga0hyeon** [comment]
Monorepo에 대해
- chromeside(현재 main), game#1, game#2, component&storybook, BE 는 모두 package 폴더 아래의 같은 depth에 위치한다
- package 폴더 아래의 모든 패키지는 node_module 을 symlink로 참조한다. 단, 각 패키지에서 개별로 필요한 module의 경우 패키지 하위의 node_module에 위치한다. 
- 화면 패키지 (chromeside, game#1, game#2) 는 component&storybook 에서 컴포넌트를 참조한다. 이것도 symlink이다.
- chromeside 패키지는 game#1, game#2 의 root component를 참조한다. 게임이 추가되면 chromeside 패키지에 참조가 추가되어야한다.

파이프라인 및 Deploy 결과에 대해
- 기대하는 Deploy 결과는 크롬익스텐션, BE, 스토리북이다.
- 크롬익스텐션의 Deploy 절차
    a. git pull & install node_modules
    b. build react
    c. build 결과물을 준비된 chrome extension template에 삽입
    d. 완성된 chrome extension 파일을 S3에 업로드
- BE Deploy 절차
    a. git pull & install node_modules
    b. zip source & zip node_modules
    c. deploy source.zip to lambda & deploy node_modules.zip to layer
    d. add, remove, modify API gateway config (필요시)
- 스토리북 Deploy 절차
    a. git pull & install node_modules
    b. build storybook
    c. deploy to S3


(추가)

- Lambda를 제외한 모든 AWS 리소스는 console을 통해 생성한다. 파이프라인에서는 AWS 리소스를 수정하거나 접근하는 작업만 수행한다.
    - 4주 안에 끝날 수 없을 것 같아 집중하고 싶은 것 (N개의 순차적인 job이 있는 파이프라인 구축해보기) 위주로 범위를 줄여보려고 합니다.
    - terraform 써서 환경별 리소스를 동적으로 생성하는 것은 다음 차수에 ㅠㅠ
    - Lambda 동적으로 생성하는것도 저한테는 굉장히 도전적일 것 같다는 느낌이 들지만.. 해보고싶습니다 ㅋㅋ


여기까지 제 생각대로라면 할 일이 이 정도로 정리 될 것 같아요.!!
- 자원 및 역할 생성
    - Chrome Extension 업로드용 S3 버킷 생성 
    - Storybook 호스트용 S3 버킷 생성 
    - API Gateway (webSocket) 생성
    - ElastiCache (Redis) 생성 
        - VPC 설정 (?) <-- 전혀 몰라서 깜깜합니다 ㅎㅎ ChatGPT 도움 받아보겠습니다
    - Github Actions에 부여할 역할 생성
        - [PUT] Chrome Extension 업로드 S3 버킷 
        - [PUT] Storybook 호스트용 S3 버킷
        - [GET, PUT, DELETE] Lambda
        - [GET, PUT] Api gateway
- Github Actions에 Pipeline 생성 (위에 보낸 그림처럼)
    - Chrome Extension
    - BE (API Gateway + Lambda)
    - Storybook

**Comment by sprinter707** [comment]
파이프라인에 대한 고민은 별도 스토리로 분리해서 정리해보는게 좋을거 같아요

찾다보니 토스나 배민에서는 yarn berry + monorepo 조합을 사용하여 관리하기도 해서 해당 사항도 같이 정리해보고 싶습니다.

**Comment by ga0hyeon** [comment]
yarn berry 가 뭔가 싶어 아주 짧게 찾아보니

의존성을 관리하는 메커니즘을 바꿈으로써 의존성 tree의 depth를 줄이면서 발생했던 side effect 를 제거한 yarn 의 (개선된) 한 줄기 정도로 이해했는데요. 비슷하게 이해하고 계신 것 맞을까요? 

맞다면 yarn --> yarn berry 마이그레이션이 해보고 싶으신걸까요?

아니면 제가 보지 못한 yarn berry 만의 monorepo 특화 기능이 있는걸까요? (왠지 머릿속에 구상하신게 있을 것 같아 10분여밖에 검색을 하지 않았어요. 질문 수준 미리 양해를 구합니다😅)

**Comment by ga0hyeon** [comment]
# Lambda 생성


![Image](https://user-images.githubusercontent.com/23169601/232372407-459137e8-3a30-4193-a5fb-f41c124b0067.png)

# Bucket 생성


![Image](https://user-images.githubusercontent.com/23169601/232372857-699a6afd-382a-4984-819c-f4fb227b9b22.png)


# VPC 및 보안그룹 생성

- [ ] 인바운드, 아웃바운드 정책에 대해 스터디하고 수정할 필요가 있음

![Image](https://user-images.githubusercontent.com/23169601/232372955-713483cb-b4dd-4821-b7df-42507eb454a0.png)




![Image](https://user-images.githubusercontent.com/23169601/232373010-97a2b141-eb6b-4c5d-8641-fe4dcbff4278.png)

# Redis 클러스터 생성
- [ ] 샤드, 노드에 대해 스터디하고 수정할 필요가 있음


![Image](https://user-images.githubusercontent.com/23169601/232373435-e5fa8c99-ab9c-49ad-bcbf-6193fcbbd347.png)
